name: slam-olfaction-mps
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pip
  # core scientific stack
  - numpy
  - scipy
  - matplotlib
  - scikit-learn
  - h5py
  - pandas
  - pyyaml
  - pytorch
  - torchvision
  - torchaudio
  - ipykernel
  - pip:
      - -e .
