kind: experiment
system:
  use_gpu: false
  torch_num_threads: 1
  log_level: DEBUG
experiment:
  type: sparsity_sweep
  model: slam
  params:

    num_osn: !!int 400
    num_potential_odors: !!int 4000

    sparsity_values:
      start: !!float 0.025
      stepsize: !!float 0.025
      end: !!float 0.6

    num_low_values:
      start: !!int 0
      stepsize: !!int 1
      end: !!int 0

    num_high_values: 
      start: !!int 20
      stepsize: !!int 1
      end: !!int 21
    error_threshold: !!float 5.0
    use_binary_search: true


    c_high: !!float 40
    c_low: !!float 0

    dt: !!float 1e-5
    t_max: !!float 0.2
    t_on_low: !!float 0
    t_on_high: !!float 0

    seed: None
    batch_size: !!int 2
    repeats: !!int 4

